### ISSUE TITLE
catalog unit stuck in 'hook failed: "config-changed"' for hours

### ISSUE THREAD

**Issue by jeffreychang911** [canonical/catalogue-k8s-operator#104]
### Bug Description

SolQA found this in our test run https://solutions.qa.canonical.com/testruns/4280456a-b75d-4c00-a498-144ad01e9f99,
while trying to deploy cos-lite bundle on top of MicroK8s 1.28 with Juju 3.5.
Crashdump here - https://oil-jenkins.canonical.com/artifacts/4280456a-b75d-4c00-a498-144ad01e9f99/generated/generated/cos/juju-crashdump-cos-2024-05-30-09.51.29.tar.gz

From juju status output we see for hours
catalogue/0*     error     idle       10.1.35.133          hook failed: "config-changed"

### To Reproduce

deploy cos-lite bundle on top of MicroK8s 1.28 with Juju 3.5.

### Environment

use juju to deploy 3 microk8s 1.28 instance on LXD, and then deploy cos-lite bundle from stable channel to that.

### Relevant log output

```shell
unit-catalogue-0: 2024-05-30 06:30:34 DEBUG juju.worker.uniter.runner starting jujuc server  {unix @/var/lib/juju/agents/unit-catalogue-0/agent.socket <nil>}
    1156 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "juju-log" for catalogue/0-config-changed-9034348731359116914
    1157 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG unit.catalogue/0.juju-log ops 2.12.0 up and running.
    1158 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "relation-ids" for catalogue/0-config-changed-9034348731359116914
    1159 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "is-leader" for catalogue/0-config-changed-9034348731359116914
    1160 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "relation-ids" for catalogue/0-config-changed-9034348731359116914
    1161 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "relation-list" for catalogue/0-config-changed-9034348731359116914
    1162 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "relation-list" for catalogue/0-config-changed-9034348731359116914
    1163 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "juju-log" for catalogue/0-config-changed-9034348731359116914
    1164 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG unit.catalogue/0.juju-log no relation on 'tracing': tracing not ready
    1165 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "juju-log" for catalogue/0-config-changed-9034348731359116914
    1166 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG unit.catalogue/0.juju-log <class '__main__.CatalogueCharm'>.<property object at 0x7fc37e8299f0> returned None; quietly disabling charm_tracing for the run.
    1167 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "juju-log" for catalogue/0-config-changed-9034348731359116914                                                                                                                                                
    1168 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG unit.catalogue/0.juju-log Emitting Juju event config_changed.
    1169 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "relation-ids" for catalogue/0-config-changed-9034348731359116914
    1170 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "relation-list" for catalogue/0-config-changed-9034348731359116914
    1171 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "relation-get" for catalogue/0-config-changed-9034348731359116914
    1172 unit-catalogue-0: 2024-05-30 06:30:35 DEBUG jujuc running hook tool "juju-log" for catalogue/0-config-changed-9034348731359116914
    1173 unit-catalogue-0: 2024-05-30 06:30:35 ERROR unit.catalogue/0.juju-log Uncaught exception while in charm code:
    1174 Traceback (most recent call last):
    1175   File "./src/charm.py", line 308, in <module>
    1176   │ main(CatalogueCharm)
    1177   File "/var/lib/juju/agents/unit-catalogue-0/charm/venv/ops/main.py", line 544, in main
    1178   │ manager.run()
    1179   File "/var/lib/juju/agents/unit-catalogue-0/charm/venv/ops/main.py", line 520, in run
    1180   │ self._emit()
    1181   File "/var/lib/juju/agents/unit-catalogue-0/charm/venv/ops/main.py", line 509, in _emit
    1182   │ _emit_charm_event(self.charm, self.dispatcher.event_name)
    1183   File "/var/lib/juju/agents/unit-catalogue-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
    1184   │ event_to_emit.emit(*args, **kwargs)
    1185   File "/var/lib/juju/agents/unit-catalogue-0/charm/venv/ops/framework.py", line 352, in emit
    1186   │ framework._emit(event)
    1187   File "/var/lib/juju/agents/unit-catalogue-0/charm/venv/ops/framework.py", line 851, in _emit
    1188   │ self._reemit(event_path)
    1189   File "/var/lib/juju/agents/unit-catalogue-0/charm/venv/ops/framework.py", line 941, in _reemit
    1190   │ custom_handler(event)
    1191   File "/var/lib/juju/agents/unit-catalogue-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 547, in wrapped_function
    1192   │ return callable(*args, **kwargs)  # type: ignore
    1193   File "/var/lib/juju/agents/unit-catalogue-0/charm/lib/charms/observability_libs/v0/cert_handler.py", line 230, in _on_config_changed
    1194   │ self._generate_csr(renew=True)
    1195   File "/var/lib/juju/agents/unit-catalogue-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 547, in wrapped_function
    1196   │ return callable(*args, **kwargs)  # type: ignore
    1197   File "/var/lib/juju/agents/unit-catalogue-0/charm/lib/charms/observability_libs/v0/cert_handler.py", line 253, in _generate_csr
    1198   │ raise RuntimeError(
    1199 RuntimeError: private key unset. call _generate_privkey() before you call this method.
    1200 unit-catalogue-0: 2024-05-30 06:30:36 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1
```

### Additional context

same exception also reported by loki
unit-loki-0: 2024-05-30 07:34:54 ERROR unit.loki/0.juju-log Uncaught exception while in charm code:                                                                                                                                                                              
   25316 Traceback (most recent call last):
   25317   File "./src/charm.py", line 658, in <module>
   25318     main(LokiOperatorCharm, use_juju_for_storage=True)
   25319   File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 544, in main
   25320     manager.run()
   25321   File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 520, in run
   25322     self._emit()                                            
   25323   File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 509, in _emit
   25324     _emit_charm_event(self.charm, self.dispatcher.event_name)
   25325   File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/main.py", line 143, in _emit_charm_event
   25326     event_to_emit.emit(*args, **kwargs)
   25327   File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 352, in emit
   25328     framework._emit(event)
   25329   File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 851, in _emit
   25330     self._reemit(event_path)
   25331   File "/var/lib/juju/agents/unit-loki-0/charm/venv/ops/framework.py", line 941, in _reemit
   25332     custom_handler(event)
   25333   File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 547, in wrapped_function
   25334     return callable(*args, **kwargs)  # type: ignore
   25335   File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/observability_libs/v0/cert_handler.py", line 230, in _on_config_changed                 
   25336     self._generate_csr(renew=True)
   25337   File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/tempo_k8s/v1/charm_tracing.py", line 547, in wrapped_function
   25338     return callable(*args, **kwargs)  # type: ignore
   25339   File "/var/lib/juju/agents/unit-loki-0/charm/lib/charms/observability_libs/v0/cert_handler.py", line 253, in _generate_csr
   25340     raise RuntimeError(
   25341 RuntimeError: private key unset. call _generate_privkey() before you call this method.
   25342 unit-loki-0: 2024-05-30 07:34:54 ERROR juju.worker.uniter.operation hook "config-changed" (via hook dispatching script: dispatch) failed: exit status 1

**Comment by dstathis** [comment]
We believe this was fixed in [revision 39](https://github.com/canonical/catalogue-k8s-operator/releases/tag/rev39). If you continue to see the issue, feel free to reopen.
