### ISSUE TITLE
Prometheus link in landing page is broken

### ISSUE THREAD

**Issue by peppepetra** [canonical/catalogue-k8s-operator#3]
My traefik external IP is 192.168.0.10 and prometheus is available at 

http://192.168.0.10/cos-lite-prometheus-0/

but the link to prometheus on the landing page is: 
http://prometheus-0.prometheus-endpoints.cos-lite.svc.cluster.local:9090/

which result in ERR_NAME_NOT_RESOLVED

**Comment by peppepetra** [comment]
Workaround: removing and adding the relation between prometheus and catalogue with:

```
juju remove-relation catalogue:catalogue prometheus:catalogue 
```
and 

```
juju remove-relation catalogue:catalogue prometheus:catalogue 
```

After that the prometheus link on landing page is the correct one:

http://192.168.0.10/cos-lite-prometheus-0

**Comment by sed-i** [comment]
New config is pushed, but workload is not restarted (nginx is not sent a HUP). Should it be? @simskij 

https://github.com/canonical/catalogue-k8s-operator/blob/3b6562b78180dcc3b585800c8d0b3b3f81bee0ec/charm/src/charm.py#L108-L110

https://github.com/canonical/catalogue-k8s-operator/blob/3b6562b78180dcc3b585800c8d0b3b3f81bee0ec/workload/nginx.conf#L18-L21

**Comment by sed-i** [comment]
Hi @peppepetra,
After the latest fetch-lib I see a correct url for prom both locally (2cpu-7gb) and in our load test (4cpu-8gb).
```
juju ssh --container catalogue catalogue/0 cat /web/config.json | jq '.apps'
```
Would you be able to confirm?

**Comment by sed-i** [comment]
Seems like the only remaining aspect of this issue is captured in https://github.com/canonical/traefik-k8s-operator/issues/111.
Closing for now.
Please feel free to reopen if you find otherwise.
