### ISSUE TITLE
Blank page when used in COS bundle

### ISSUE THREAD

**Issue by samuelengineer** [canonical/catalogue-k8s-operator#34]
Catalogue, when deployed in the COS bundle, is served through traefik, at a non-root url - /cos-catalogue .  However, in this configuration, the catalogue web ui still tries to load page assets from the root url.

For example, if catalogue is being served at http://172.27.64.71/cos-catalogue , it tries to load ui.js from: http://172.27.64.71/ui.js

But it should load it from: http://172.27.64.71/cos-catalogue/ui.js

**Comment by simskij** [comment]
Resolved in resource revision `24`, currently on `latest/edge`

**Comment by simskij** [comment]
> @simskij thanks, would you have advice for how to upgrade the charm to get that revision? I ran `juju refresh catalogue --channel latest/edge`, but the image still has the old index.html. Juju resources shows that it is indeed using revision 24 of the image, but the app doesn't show that change. Even if I `juju scale-application catalogue 0`, then scale back to 1 to recreate the pod.

You're on microk8s I'll assume? Could be that you'll have to use `microk8s ctr` to re-pull the image as it might be cached.
