### ISSUE TITLE
No information about the endpoint of catalogue

### ISSUE THREAD

**Issue by nobuto-m** [canonical/catalogue-k8s-operator#70]
### Bug Description

The catalogue operator offers a nice landing page for services behind traefix such as Grafana, Prometheus, and Alertmanager in COS.

However, there is a little to no hint on how to access to the end point of catalogue. As you can see it in the tutorial, there is no information about the catalogue endpoint.

https://charmhub.io/topics/canonical-observability-stack/tutorials/install-microk8s#heading--deploy-the-cos-lite-bundle
```

App           Version  Status  Scale  Charm             Channel  Rev  Address         Exposed  Message
alertmanager  0.25.0   active      1  alertmanager-k8s  edge      67  10.152.183.93   no       
catalogue              active      1  catalogue-k8s     edge      15  10.152.183.193  no       
grafana       9.2.1    active      1  grafana-k8s       edge      77  10.152.183.137  no       
loki          2.7.4    active      1  loki-k8s          edge      82  10.152.183.119  no       
prometheus    2.42.0   active      1  prometheus-k8s    edge     122  10.152.183.51   no       
traefik       2.9.6    active      1  traefik-k8s       edge     125  10.43.8.34      no       

Unit             Workload  Agent  Address     Ports  Message
alertmanager/0*  active    idle   10.1.55.34         
catalogue/0*     active    idle   10.1.55.38         
grafana/0*       active    idle   10.1.55.32         
loki/0*          active    idle   10.1.55.14         
prometheus/0*    active    idle   10.1.55.40         
traefik/0*       active    idle   10.1.55.53         
```

Can the juju status have the endpoint URL in the status message for example? So the first user experience could be better instead of querying the endpoint with jq or grep.
https://charmhub.io/topics/canonical-observability-stack/tutorials/install-microk8s#heading--browse-dashboards

### To Reproduce

1. juju deploy --trust cos-lite on microk8s

### Environment

N/A

### Relevant log output

```shell
N/A
```

**Comment by simskij** [comment]
I think the idea is sound, but we shouldn't use status messages. Instead, we should put it as an action.
